runtime: nodejs
env: flex
resources:
  cpu: .9
  memory_gb: 0.58
  disk_size_gb: 10
manual_scaling:
  instances: 1
env_variables:
  NODE_ENV: production
handlers:
  - url: /*
    secure: always
    redirect_http_response_code: 301
    script: server.js
