name: build-and-deploy-on-push

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [10]

    steps:
     - uses: actions/checkout@v1
     - name: Use Node.js ${{ matrix.node_version }}
       uses: actions/setup-node@v1
       with:
         version: ${{ matrix.node_version }}

     - name: BUILD PRODUCTION
       run: |
         npm install
         npm run build
       env:
         NODE_ENV: Production

     - name: Setup Google Cloud
       uses: actions/gcloud/auth@master
       env:
         GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

     - name: Deploy
       uses: actions/gcloud/cli@master
       env:
         CLOUDSDK_CORE_PROJECT: ${{ secrets.GCLOUD_PROJECT_ID }}
       with:
         args: app deploy app.yaml --quiet --version v1
